version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  say-hello:
    docker:
      - image: cimg/python:3.10.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
